repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.62.3
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs
        args:
          - '--args=--lockfile=false'
      - id: terraform_tflint
        args:
          - '--args=--only=terraform_deprecated_interpolation'
          - '--args=--only=terraform_deprecated_index'
          - '--args=--only=terraform_unused_declarations'
          - '--args=--only=terraform_comment_syntax'
          - '--args=--only=terraform_documented_outputs'
          - '--args=--only=terraform_documented_variables'
          - '--args=--only=terraform_typed_variables'

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.22
    hooks:
      - id: terragrunt-hclfmt
        name: Terragrunt hclfmt
        description: Rewrites all Terragrunt configuration files to a canonical format
        entry: hooks/terragrunt-hclfmt.sh
        language: script
        files: \.hcl$
        exclude: >
          (?x)^(
            .+\.terraform\/.*$|
            .+\.terragrunt-cache\/.*$|
          )$
      - id: shellcheck
        name: Shellcheck Bash Linter
        description: Performs linting on bash scripts
        entry: hooks/shellcheck.sh
        language: script

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
