/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/posts': {
    /** List Posts */
    get: operations['listPosts'];
    /** Create a new Post */
    post: operations['createPost'];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    BasePost: {
      title: string;
      description: string;
      /** Format: date-time */
      publishedDate: string;
      content: string;
    };
    Post: components['schemas']['BasePost'] & {
      id: string;
      /** Format: date-time */
      createdDate: string;
      /** Format: date-time */
      updatedDate: string;
    };
    CreatePostRequestBody: components['schemas']['BasePost'];
    ListPostsResponseBody: components['schemas']['Post'][];
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /** List Posts */
  listPosts: {
    requestBody: {
      content: {
        'application/json': components['schemas']['CreatePostRequestBody'];
      };
    };
    responses: {
      /** @description Retrieve the list of Posts */
      200: {
        content: {
          'application/json': components['schemas']['ListPostsResponseBody'];
        };
      };
    };
  };
  /** Create a new Post */
  createPost: {
    responses: {
      /** @description Success */
      200: {
        content: {
          'application/json': components['schemas']['Post'];
        };
      };
    };
  };
}
